// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var callWithFinally = ((fn, finallyCb) => {
    try {
      return fn()
    } finally {
      finallyCb()
    }
  });

function initialNotify(context) {
  var iterator = context.q;
  context.q = [];
  for(var effectsIdx = 0 ,effectsIdx_finish = iterator.length; effectsIdx < effectsIdx_finish; ++effectsIdx){
    var effects = iterator[effectsIdx];
    for(var effectIdx = 0 ,effectIdx_finish = effects.length; effectIdx < effectIdx_finish; ++effectIdx){
      effects[effectIdx]();
    }
  }
}

var context = {
  r: undefined,
  u: undefined,
  q: [],
  v: 0,
  p: undefined,
  n: initialNotify
};

function getNotify(param) {
  if (context.n === initialNotify) {
    return function () {
      return initialNotify(context);
    };
  } else {
    return context.n;
  }
}

function setNotify(notify) {
  context.n = notify;
}

function make(initial) {
  var valueAct = {
    a: initial,
    v: -1,
    e: [],
    g: undefined,
    s: undefined
  };
  valueAct.g = (function (param) {
      if (valueAct.v !== context.v) {
        valueAct.v = context.v;
        var match = context.u;
        var match$1 = context.r;
        if (match !== undefined) {
          valueAct.e.splice(valueAct.e.indexOf(match), 1);
        } else if (match$1 !== undefined) {
          valueAct.e.push(match$1);
        }
        
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: valueAct,
              s: valueAct.a
            });
      }
      return valueAct.a;
    });
  valueAct.s = (function (state) {
      valueAct.a = state;
      if (context.q.push(valueAct.e) === 1) {
        Promise.resolve(undefined).then(function (param) {
              getNotify(undefined)();
            });
      }
      valueAct.e = [];
      if (valueAct.v !== context.v) {
        valueAct.v = context.v;
        var match = context.u;
        var match$1 = context.r;
        if (match !== undefined) {
          valueAct.e.splice(valueAct.e.indexOf(match), 1);
        } else if (match$1 !== undefined) {
          valueAct.e.push(match$1);
        }
        
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: valueAct,
              s: valueAct.a
            });
        return ;
      }
      
    });
  return valueAct;
}

function computed(fn) {
  var computedAct = {
    a: undefined,
    v: -1,
    p: [],
    g: undefined,
    s: (function (param) {
        throw new Error("Act.set is not supported for computed acts.");
      })
  };
  computedAct.g = (function (param) {
      if (computedAct.v !== context.v || context.r === undefined) {
        var computedPubs = computedAct.p;
        var prevPubs = context.p;
        context.p = undefined;
        var isEmptyComputedPubs = computedPubs.length === 0;
        if (isEmptyComputedPubs || computedPubs.some(function (el) {
                return el.a.g(undefined) !== el.s;
              })) {
          var newPubs = isEmptyComputedPubs ? computedPubs : [];
          context.p = newPubs;
          computedAct.p = newPubs;
          computedAct.a = fn(undefined);
        }
        context.p = prevPubs;
        computedAct.v = context.v;
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: computedAct,
              s: computedAct.a
            });
      }
      return computedAct.a;
    });
  return computedAct;
}

function subscribe(act, cb) {
  var subscribtionContext = {
    q: cb,
    s: cb
  };
  var effect = function () {
    if (subscribtionContext.q === context.q) {
      return ;
    }
    subscribtionContext.q = context.q;
    context.v = context.v + 1;
    var prevRoot = context.r;
    context.r = effect;
    return callWithFinally((function () {
                  var calculatedState = act.g();
                  if (subscribtionContext.s !== calculatedState) {
                    subscribtionContext.s = calculatedState;
                    return cb(calculatedState);
                  }
                  
                }), (function () {
                  context.r = prevRoot;
                }));
  };
  effect();
  return function (param) {
    context.v = context.v + 1;
    context.u = effect;
    act.g();
    context.u = undefined;
  };
}

exports.make = make;
exports.computed = computed;
exports.subscribe = subscribe;
exports.getNotify = getNotify;
exports.setNotify = setNotify;
/* No side effect */
