// Generated by ReScript, PLEASE EDIT WITH CARE


function make(initial) {
  return {
          s: initial,
          e: []
        };
}

function get(act) {
  return act.s;
}

function set(act, state) {
  act.s = state;
}

export {
  make ,
  get ,
  set ,
}
/* No side effect */
