// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Act from "./Act.bs.mjs";
import * as Uvu from "uvu";
import * as Assert from "uvu/assert";

Uvu.test("[ReScript] read outside effect stale computed", (function (param) {
        var a = Act.make(0);
        Assert.is(Act.get(a), 0);
        Act.set(a, 1);
        Assert.is(Act.get(a), 1);
      }));

Uvu.test.run();

export {
  
}
/*  Not a pure module */
