// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Act = require("../src/Act.bs.js");
var Ava = require("ava").default;

Ava("[ReScript] read outside effect stale computed", (function (t) {
        var a = Act.make(0);
        t.is(Act.get(a), 0, undefined);
        Act.set(a, 1);
        t.is(Act.get(a), 1, undefined);
      }));

Ava("[ReScript] redefine act.notify", (async function (t) {
        var notify = Act.getNotify(undefined);
        Act.setNotify(function () {
              setTimeout((function (param) {
                      notify();
                    }), 0);
            });
        var a = Act.make(0);
        var callsRef = {
          contents: 0
        };
        Act.subscribe(a, (function (param) {
                callsRef.contents = callsRef.contents + 1 | 0;
              }));
        t.is(callsRef.contents, 1, undefined);
        Act.set(a, 123);
        await Promise.resolve(undefined);
        t.is(callsRef.contents, 1, undefined);
        await new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        resolve(undefined);
                      }), 0);
              }));
        t.is(callsRef.contents, 2, undefined);
      }));

/*  Not a pure module */
